name: CD

on: push

env:
  CI: true
  CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master # this will use by default the .ruby-version file

      - run: ruby -v
      - run: gem install --no-document bundler
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rspec

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set environment from cloudtruth
        uses: cloudtruth/configure-action@v1
        with:
          token: "${{ secrets.CLOUDTRUTH_API_KEY }}"
          project: "deploy"
          environment: "production"

      - name: Build the Docker image
        run: |
          docker build --target release -t importer .

      - name: Push the Docker image
        run: |
          tag=${GITHUB_REF##*/v}
          echo "Pushing version '$tag' to docker hub"
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

          docker tag importer cloudtruth/importer:latest
          docker push cloudtruth/importer:latest
          docker tag importer cloudtruth/importer:${tag}
          docker push cloudtruth/importer:${tag}
